### ISSUE TITLE
Saving a file when a save-commands.json file is not present causes an error in Atom

### ISSUE THREAD

**Issue by cemulate** [JsonHunt/save-commands#38]
It should probably just silently do nothing instead - not every directory I open with Atom will have/need a save-commands.json file.

**Comment by mvila** [comment]
Since this repository has been abandoned by his author, I created a plugin doing the same thing with a simpler interface: https://github.com/mvila/on-save

**Comment by JsonHunt** [comment]
this is now resolved

**Comment by chinochano** [comment]
Hi @JsonHunt,

For some reason, I still get

`Uncaught (in promise) Missing config file save-commands.json on the path`

when saving in a directory without a save-commands.json config file. This error is rendering my FTP package - [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) - useless.

The funny part is my issue disappears after disabling and enabling save-commands package. After that, it still throws the same error, but it does so *after* my ftp package has performed on the file.
